# Generated by Django 6.1.1 on 2026-09-28 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_expiry', models.DateField(blank=True, null=True)),
                ('duty_status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('ON_DUTY_AVAILABLE', 'On Duty (Available)'), ('ON_TRIP', 'On Active Trip'), ('SUSPENDED', 'Suspended / Inactive')], default='OFF_DUTY', max_length=20)),
                ('safety_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Safety score out of 100', max_digits=5)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_driver', to='fleet.vehicle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField(auto_now_add=True)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('start_odometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pre_inspection_passed', models.BooleanField(default=True)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Shift'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_logs', to='drivers.driverprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_logs', to='fleet.vehicle')),
            ],
        ),
    ]
