# Generated by Django 6.1.1 on 2026-09-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Driver Avatar Photo URL', max_length=500, null=True),
        ),
    ]
