CREATE TABLE IF NOT EXISTS `custom_enquiries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enquiry_id` varchar(50) NOT NULL,
  `customer_name` varchar(255) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `whatsapp` varchar(50) DEFAULT NULL,
  `departure_city` varchar(255) DEFAULT NULL,
  `destinations` varchar(500) DEFAULT NULL,
  `travel_dates` varchar(255) DEFAULT NULL,
  `flexible_dates` tinyint(1) DEFAULT 0,
  `adults` int(11) DEFAULT 2,
  `children` int(11) DEFAULT 0,
  `infants` int(11) DEFAULT 0,
  `budget_range` varchar(255) DEFAULT NULL,
  `hotel_category` varchar(255) DEFAULT NULL,
  `room_type` varchar(255) DEFAULT NULL,
  `meal_pref` varchar(255) DEFAULT NULL,
  `req_flight` tinyint(1) DEFAULT 0,
  `req_train` tinyint(1) DEFAULT 0,
  `req_car` tinyint(1) DEFAULT 0,
  `req_bike` tinyint(1) DEFAULT 0,
  `req_airport_pickup` tinyint(1) DEFAULT 0,
  `req_sightseeing` tinyint(1) DEFAULT 0,
  `req_adventure` tinyint(1) DEFAULT 0,
  `trip_type` varchar(255) DEFAULT NULL,
  `special_requests` text DEFAULT NULL,
  `documents_json` text DEFAULT NULL,
  `status` varchar(100) DEFAULT 'New Enquiry',
  `assigned_to` varchar(255) DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `enquiry_id` (`enquiry_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `enquiry_timeline` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enquiry_id` varchar(50) NOT NULL,
  `action_type` varchar(255) NOT NULL,
  `notes` text DEFAULT NULL,
  `follow_up_date` date DEFAULT NULL,
  `attachment_url` varchar(500) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT 'System',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `enquiry_id` (`enquiry_id`),
  CONSTRAINT `fk_enquiry` FOREIGN KEY (`enquiry_id`) REFERENCES `custom_enquiries` (`enquiry_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vendor_payment_methods` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `vendor_id` varchar(100) NOT NULL,
  `method_type` varchar(100) NOT NULL,
  `display_name` varchar(255) NOT NULL,
  `account_name` varchar(255) DEFAULT NULL,
  `bank_name` varchar(255) DEFAULT NULL,
  `account_number` varchar(255) DEFAULT NULL,
  `ifsc_code` varchar(255) DEFAULT NULL,
  `upi_id` varchar(255) DEFAULT NULL,
  `qr_image_url` varchar(500) DEFAULT NULL,
  `instructions` text DEFAULT NULL,
  `status` varchar(50) DEFAULT 'Active',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
