# Generated by Django 6.1.1 on 2026-09-29 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_driverprofile_avatar_url'),
        ('fleet', '0006_alter_vehiclecompliance_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Corporate Enterprise / Hotel / Airline Account Name', max_length=150, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=25)),
                ('gstin', models.CharField(blank=True, help_text='Goods & Services Tax Identification Number', max_length=20, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('credit_limit_inr', models.DecimalField(decimal_places=2, default=500000.0, help_text='Corporate Credit Buffer (₹)', max_digits=12)),
                ('payment_terms_days', models.PositiveIntegerField(default=30, help_text='Net 30 / Net 45 Payment Terms')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(help_text='e.g. DISP-2026-1001', max_length=40, unique=True)),
                ('booking_type', models.CharField(choices=[('AIRPORT_TRANSFER', 'Airport Flight Transfer'), ('CORP_CHARTER', 'Executive Charter (8h / 80km)'), ('EMPLOYEE_SHUTTLE', 'Employee Roaster Dispatch'), ('INTERCITY', 'Outstation Business Delegation'), ('POINT_TO_POINT', 'Point-to-Point City Transfer')], default='AIRPORT_TRANSFER', max_length=30)),
                ('vehicle_class_requested', models.CharField(choices=[('SEDAN', 'Executive Sedan'), ('SUV', 'Premium SUV'), ('EV', 'Electric Vehicle'), ('VAN', 'Multi-Passenger Van'), ('LUXURY', 'Luxury Class')], default='SEDAN', max_length=20)),
                ('pickup_time', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('flight_number', models.CharField(blank=True, help_text='e.g. 6E-241 Indigo', max_length=30, null=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=25)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Allocation'), ('DISPATCHED', 'Dispatched / En Route'), ('ON_TRIP', 'Active Trip (Meter Running)'), ('COMPLETED', 'Completed & Invoiced'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25)),
                ('start_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('end_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('base_rate_inr', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('extra_km_rate_inr', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('extra_km_charge_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('toll_parking_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_gst_inr', models.DecimalField(decimal_places=2, default=0.0, help_text='5% GST on transport', max_digits=10)),
                ('total_fare_inr', models.DecimalField(decimal_places=2, default=2625.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='drivers.driverprofile')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='fleet.vehicle')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='dispatches.corporateclient')),
            ],
        ),
    ]
