# Generated by Django 6.1.1 on 2026-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for trip cancellation', null=True),
        ),
        migrations.AddField(
            model_name='dispatchbooking',
            name='cancelled_by',
            field=models.CharField(blank=True, help_text='User or role who cancelled the dispatch', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchbooking',
            name='booking_reference',
            field=models.CharField(blank=True, help_text='e.g. DISP-2026-1001', max_length=40, unique=True),
        ),
    ]
