# Generated by Django 6.1.1 on 2026-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatches', '0002_dispatchbooking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchbooking',
            name='vehicle_class_requested',
            field=models.CharField(choices=[('SEDAN', 'Executive Sedan'), ('SUV', 'Premium SUV'), ('PREMIUM_MPV', 'Premium MPV / Innova'), ('EV', 'Electric Vehicle'), ('VAN', 'Multi-Passenger Van'), ('LUXURY', 'Luxury Class')], default='SEDAN', max_length=20),
        ),
    ]
