# Generated by Django 6.1.1 on 2026-09-28 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(help_text='License Plate Registration Number', max_length=30, unique=True)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=50, unique=True)),
                ('make', models.CharField(help_text='e.g. Toyota, Hyundai, Tata', max_length=50)),
                ('model', models.CharField(help_text='e.g. Camry, Innova Crysta, Tigor EV', max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_class', models.CharField(choices=[('SEDAN', 'Executive Sedan'), ('SUV', 'Premium SUV'), ('EV', 'Electric Vehicle'), ('VAN', 'Multi-Passenger Van'), ('LUXURY', 'Luxury Class')], default='SEDAN', max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric (EV)')], default='DIESEL', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Assignment'), ('ON_DUTY', 'On Duty / Dispatched'), ('IN_MAINTENANCE', 'In Maintenance'), ('DECOMMISSIONED', 'Decommissioned')], default='AVAILABLE', max_length=20)),
                ('current_odometer', models.DecimalField(decimal_places=2, default=0.0, help_text='Current Odometer Reading (KM)', max_digits=10)),
                ('seating_capacity', models.PositiveIntegerField(default=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PUC', 'Pollution Under Control Certificate'), ('INSURANCE', 'Vehicle Insurance Policy'), ('FITNESS', 'Fitness Certificate'), ('PERMIT', 'Commercial Transport Permit'), ('TAX_REC', 'Road Tax Receipt')], max_length=20)),
                ('document_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('issuer_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_docs', to='fleet.vehicle')),
            ],
        ),
    ]
