# Generated by Django 6.1.1 on 2026-09-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of gallery image URLs (Front, Side, Rear, Interior)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(blank=True, help_text='Main Vehicle Thumbnail Image URL', max_length=500, null=True),
        ),
    ]
