# Generated by Django 6.1.1 on 2026-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_gallery_images_alter_vehicle_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='extra_km_rate_inr',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Extra KM Rate in INR (₹)', max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of vehicle features & telematics equipment'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='shift_rate_inr',
            field=models.DecimalField(decimal_places=2, default=2500.0, help_text='Shift Rate in INR (₹)', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(default='AUTOMATIC', help_text='AUTOMATIC / MANUAL', max_length=20),
        ),
    ]
