# Generated by Django 6.1.1 on 2026-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicle_extra_km_rate_inr_vehicle_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of gallery image URLs or Data URIs'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.TextField(blank=True, help_text='Main Vehicle Thumbnail Image URL or Data URI', null=True),
        ),
    ]
