# Generated by Django 6.1.1 on 2026-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alter_vehicle_gallery_images_alter_vehicle_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecompliance',
            name='document_type',
            field=models.CharField(choices=[('RC_BOOK', 'Registration Certificate (RC Book)'), ('PUC', 'Pollution Under Control Certificate'), ('INSURANCE', 'Vehicle Insurance Policy'), ('FITNESS', 'Fitness Certificate'), ('PERMIT', 'Commercial Transport Permit'), ('TAX_REC', 'Road Tax Receipt')], max_length=20),
        ),
    ]
