# Generated by Django 6.1.1 on 2026-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_alter_vehiclecompliance_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric (EV)'), ('HYBRID', 'Strong Hybrid')], default='DIESEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(choices=[('SEDAN', 'Executive Sedan'), ('SUV', 'Premium SUV'), ('PREMIUM_MPV', 'Premium MPV / Innova'), ('EV', 'Electric Vehicle'), ('VAN', 'Multi-Passenger Van'), ('LUXURY', 'Luxury Class')], default='SEDAN', max_length=20),
        ),
    ]
