# Generated by Django 6.1.1 on 2026-10-07 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0006_alter_vehiclecompliance_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('zone_type', models.CharField(choices=[('AIRPORT', 'International Airport Hub'), ('HOTEL_CLUSTER', 'Luxury Resort & Hotel Cluster'), ('TECH_PARK', 'Corporate Tech Park / DC'), ('DEPOT', 'Fleet Operations Hub / Depot'), ('RESTRICTED', 'Restricted / Low-Speed Zone')], default='TECH_PARK', max_length=30)),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meters', models.PositiveIntegerField(default=1200, help_text='Circular geofence radius in meters')),
                ('speed_limit_kmh', models.PositiveIntegerField(default=60, help_text='Maximum permissible speed inside zone')),
                ('color_hex', models.CharField(default='#1e293b', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelematicsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('OVERSPEEDING', 'Speed Governor Limit Exceeded'), ('GEOFENCE_ENTER', 'Entered Operational Geofence'), ('GEOFENCE_EXIT', 'Exited Operational Geofence'), ('IDLE_TIMEOUT', 'Excessive Engine Idle (>15 mins)'), ('HARD_BRAKING', 'Harsh Acceleration / Braking Event'), ('SOS_EMERGENCY', 'SOS Driver / Passenger Panic Alert')], default='OVERSPEEDING', max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning Alert'), ('CRITICAL', 'Critical High Priority')], default='WARNING', max_length=15)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('message', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telematics_alerts', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('heading', models.PositiveSmallIntegerField(default=0, help_text='Bearing 0-360 degrees')),
                ('engine_status', models.CharField(choices=[('RUNNING', 'Engine Running / In Motion'), ('IDLE', 'Idling (Engine ON, Stopped)'), ('OFF', 'Ignition OFF')], default='IDLE', max_length=15)),
                ('battery_pct', models.DecimalField(decimal_places=2, default=96.0, max_digits=5)),
                ('fuel_pct', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('odometer_km', models.DecimalField(decimal_places=2, default=12000.0, max_digits=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles', to='telematics.geofencezone')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='telematics__vehicle_ed2bbb_idx')],
            },
        ),
    ]
