# Generated by Django 6.1.1 on 2026-10-08 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_alter_vehicle_fuel_type_alter_vehicle_vehicle_class'),
        ('telematics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telematicsalert',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telematics_alerts', to='fleet.vehicle'),
        ),
    ]
