# Generated by Django 6.1.1 on 2026-10-07 10:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatches', '0001_initial'),
        ('drivers', '0002_driverprofile_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('subtotal_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('toll_reimbursements_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('amount_paid_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('amount_due_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Client'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('DISPUTED', 'Disputed')], default='DRAFT', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=80, null=True)),
                ('payment_mode', models.CharField(blank=True, help_text='NEFT / RTGS / Cheque / UPI', max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookings', models.ManyToManyField(blank=True, limit_choices_to={'status': 'COMPLETED'}, related_name='invoices', to='dispatches.dispatchbooking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='dispatches.corporateclient')),
            ],
            options={
                'ordering': ['-billing_period_end'],
            },
        ),
        migrations.CreateModel(
            name='DriverPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('total_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('base_pay_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('incentive_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pay_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='PENDING', max_length=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='drivers.driverprofile')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ContractPricingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('AIRPORT_TRANSFER', 'Airport Flight Transfer'), ('CORP_CHARTER', 'Executive Charter (8h/80km)'), ('EMPLOYEE_SHUTTLE', 'Employee Roaster Dispatch'), ('INTERCITY', 'Outstation Business Delegation'), ('POINT_TO_POINT', 'Point-to-Point City Transfer')], max_length=30)),
                ('vehicle_class', models.CharField(max_length=20)),
                ('base_rate_inr', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('extra_km_rate_inr', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('included_km', models.PositiveIntegerField(default=40, help_text='Free km included in base rate')),
                ('night_surcharge_pct', models.DecimalField(decimal_places=2, default=15.0, help_text='Night surcharge %', max_digits=5)),
                ('weekend_surcharge_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=5.0, help_text='GST % on transport', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_cards', to='dispatches.corporateclient')),
            ],
            options={
                'ordering': ['client__name', 'service_type'],
                'unique_together': {('client', 'service_type', 'vehicle_class')},
            },
        ),
    ]
